# application.yml
server:
  port: 8094
spring:
  profiles:
    active: production
---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/impo_app_test
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/impo_app_dev
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:mysql://localhost:3306/impo_app_db
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  main:
    web-application-type: none
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
server:
  servlet:
    context-path: /impot
  port: 8080
